import { MigrationInterface, QueryRunner } from "typeorm";

export class CreateInital1760689749034 implements MigrationInterface {
    name = 'CreateInital1760689749034'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "role" ("created_by" character varying, "updated_by" character varying, "deleted_by" character varying, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" character varying, CONSTRAINT "UQ_ae4578dcaed5adff96595e61660" UNIQUE ("name"), CONSTRAINT "PK_b36bcfe02fc8de3c57a8b2391c2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user" ("created_by" character varying, "updated_by" character varying, "deleted_by" character varying, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "id" uuid NOT NULL, "username" character varying NOT NULL, "employeeId" character varying NOT NULL, "email" character varying NOT NULL, "firstnameThai" character varying, "lastnameThai" character varying, "firstnameEng" character varying, "lastnameEng" character varying, "securityCount" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_cace4a159ff9f2512dd42373760" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_e12875dfb3b1d92d7d7c5377e2" ON "user" ("email") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_78a916df40e02a9deb1c4b75ed" ON "user" ("username") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_ab4a80281f1e8d524714e00f38" ON "user" ("employeeId") `);
        await queryRunner.query(`CREATE TABLE "product_option_value" ("created_by" character varying, "updated_by" character varying, "deleted_by" character varying, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "product_option_id" uuid NOT NULL, "value" character varying(100) NOT NULL, "price" numeric(10,2) NOT NULL DEFAULT '0', "image" character varying(255), CONSTRAINT "PK_2ab71ed3b21be5800905c621535" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "product_option" ("created_by" character varying, "updated_by" character varying, "deleted_by" character varying, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "product_id" uuid NOT NULL, "name" character varying(100) NOT NULL, CONSTRAINT "PK_4cf3c467e9bc764bdd32c4cd938" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "category" ("created_by" character varying, "updated_by" character varying, "deleted_by" character varying, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "product_type_id" uuid NOT NULL, "name" character varying(255) NOT NULL, "description" text, CONSTRAINT "PK_9c4e4a89e3674fc9f382d733f03" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "product_type" ("created_by" character varying, "updated_by" character varying, "deleted_by" character varying, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "code" character varying(10) NOT NULL DEFAULT 'FUR', "name" character varying(255) NOT NULL, "description" text, CONSTRAINT "UQ_69a52b82458769a4d2ab1835b62" UNIQUE ("code"), CONSTRAINT "UQ_8978484a9cee7a0c780cd259b88" UNIQUE ("name"), CONSTRAINT "PK_e0843930fbb8854fe36ca39dae1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "package_detail" ("product_id" uuid NOT NULL, "projectId" uuid NOT NULL, "modelId" uuid NOT NULL, CONSTRAINT "PK_ef0b311e54e5f14c64099bd6fee" PRIMARY KEY ("product_id"))`);
        await queryRunner.query(`CREATE TYPE "public"."product_item_type_enum" AS ENUM('PRODUCT', 'PACKAGE')`);
        await queryRunner.query(`CREATE TABLE "product" ("created_by" character varying, "updated_by" character varying, "deleted_by" character varying, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL, "description" text, "product_type_id" uuid, "category_id" uuid, "item_type" "public"."product_item_type_enum" NOT NULL DEFAULT 'PRODUCT', CONSTRAINT "PK_bebc9158e480b949565b4dc7a82" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "product_variant_image" ("created_by" character varying, "updated_by" character varying, "deleted_by" character varying, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "product_variant_id" uuid NOT NULL, "file_cur_name" character varying(255), "file_prev_name" character varying(255), "file_extension" character varying(10), "alt_text" character varying(255), "is_main" boolean NOT NULL DEFAULT false, "sort_order" integer NOT NULL DEFAULT '0', "file_path" character varying NOT NULL, "file_bucket" character varying NOT NULL, CONSTRAINT "PK_e768b1a1fe30fe0aa9cc54b1a83" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "product_variant" ("created_by" character varying, "updated_by" character varying, "deleted_by" character varying, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "product_id" uuid NOT NULL, "sku" character varying(100) NOT NULL, "sellingPrice" numeric(10,2) NOT NULL, "budgetPrice" numeric(10,2) NOT NULL, "stock" integer NOT NULL DEFAULT '0', CONSTRAINT "UQ_f4dc2c0888b66d547c175f090e2" UNIQUE ("sku"), CONSTRAINT "PK_1ab69c9935c61f7c70791ae0a9f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "package_item" ("created_by" character varying, "updated_by" character varying, "deleted_by" character varying, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "product_id" uuid NOT NULL, "product_variant_id" uuid NOT NULL, "quantity" integer NOT NULL, "special_price" integer NOT NULL, "seq" integer NOT NULL, "package_seq" integer NOT NULL, "type" "public"."package_item_type_enum" NOT NULL DEFAULT 'DEFAULT', CONSTRAINT "PK_b9830060b4e555fe0e1bd97b577" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "quotation_item" ("created_by" character varying, "updated_by" character varying, "deleted_by" character varying, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "id" character varying NOT NULL DEFAULT uuidv7(), "product_type" "public"."quotation_item_product_type_enum" NOT NULL DEFAULT 'PRODUCT', "quotation_id" character varying NOT NULL, "product_id" uuid, "package_id" uuid, "quantity" integer NOT NULL DEFAULT '0', "special_price" numeric(18,2), "unit_price" numeric(18,2) NOT NULL DEFAULT '0', "total_price" numeric(18,2) NOT NULL DEFAULT '0', CONSTRAINT "PK_c7f10065ad2a53e2fb08919c3c3" PRIMARY KEY ("id")); COMMENT ON COLUMN "quotation_item"."product_type" IS 'ประเภทสินค้า'; COMMENT ON COLUMN "quotation_item"."quotation_id" IS 'รหัสใบเสนอราคา'; COMMENT ON COLUMN "quotation_item"."product_id" IS 'รหัสสินค้า'; COMMENT ON COLUMN "quotation_item"."package_id" IS 'รหัสชุดสินค้า'; COMMENT ON COLUMN "quotation_item"."quantity" IS 'จำนวนสินค้า'; COMMENT ON COLUMN "quotation_item"."special_price" IS 'ราคาพิเศษ'; COMMENT ON COLUMN "quotation_item"."unit_price" IS 'ราคา/หน่วย'; COMMENT ON COLUMN "quotation_item"."total_price" IS 'ราคารวม'`);
        await queryRunner.query(`CREATE TABLE "quotation" ("created_by" character varying, "updated_by" character varying, "deleted_by" character varying, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "id" character varying NOT NULL DEFAULT uuidv7(), "status" "public"."quotation_status_enum" NOT NULL DEFAULT 'PENDING', "date" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "code" character varying NOT NULL, "customer_first_name" character varying, "customer_last_name" character varying, "customer_phone" character varying, "customer_email" character varying, "customer_address" text, "project_id" character varying NOT NULL, "unit_id" character varying NOT NULL, "unit_number" character varying NOT NULL, CONSTRAINT "UQ_4c3973c666b05afaf4ff9d140be" UNIQUE ("code"), CONSTRAINT "PK_596c572d5858492d10d8cf5383d" PRIMARY KEY ("id")); COMMENT ON COLUMN "quotation"."date" IS 'วันที่ใบเสนอราคา'; COMMENT ON COLUMN "quotation"."code" IS 'รหัสใบเสนอราคา'; COMMENT ON COLUMN "quotation"."customer_first_name" IS 'ชื่อลูกค้า'; COMMENT ON COLUMN "quotation"."customer_last_name" IS 'นามสกุลลูกค้า'; COMMENT ON COLUMN "quotation"."customer_phone" IS 'หมายเลขโทรศัพท์ลูกค้า'; COMMENT ON COLUMN "quotation"."customer_email" IS 'อีเมลลูกค้า'; COMMENT ON COLUMN "quotation"."customer_address" IS 'ที่อยู่ลูกค้า'; COMMENT ON COLUMN "quotation"."project_id" IS 'รหัสโครงการ'; COMMENT ON COLUMN "quotation"."unit_id" IS 'รหัสยูนิต'; COMMENT ON COLUMN "quotation"."unit_number" IS 'หมายเลขยูนิต'`);
        await queryRunner.query(`CREATE TABLE "file" ("created_by" character varying, "updated_by" character varying, "deleted_by" character varying, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "ref_id" character varying NOT NULL, "file_name" character varying NOT NULL, "file_path" character varying NOT NULL, "file_bucket" character varying NOT NULL, "is_public" boolean NOT NULL, "project_id" character varying(15), CONSTRAINT "PK_36b46d232307066b3a2c9ea3a1d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c839fa149d39efa6217eee7414" ON "file" ("ref_id") `);
        await queryRunner.query(`CREATE TABLE "user_roles" ("user_id" uuid NOT NULL, "role_id" uuid NOT NULL, CONSTRAINT "PK_23ed6f04fe43066df08379fd034" PRIMARY KEY ("user_id", "role_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_87b8888186ca9769c960e92687" ON "user_roles" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_b23c65e50a758245a33ee35fda" ON "user_roles" ("role_id") `);
        await queryRunner.query(`CREATE TABLE "variant_option_values" ("product_variant_id" uuid NOT NULL, "product_option_value_id" uuid NOT NULL, CONSTRAINT "PK_469ae613f727a69420f7caf2817" PRIMARY KEY ("product_variant_id", "product_option_value_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_05d823f52ff66d4149a5cd784d" ON "variant_option_values" ("product_variant_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_0f99ccde035292117268b3fa2a" ON "variant_option_values" ("product_option_value_id") `);
        await queryRunner.query(`ALTER TABLE "product_option_value" ADD CONSTRAINT "FK_975b6e2a1b5de96875fa1c84413" FOREIGN KEY ("product_option_id") REFERENCES "product_option"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_option" ADD CONSTRAINT "FK_e634fca34f6b594b87fdbee95f6" FOREIGN KEY ("product_id") REFERENCES "product"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "category" ADD CONSTRAINT "FK_a6d080a3ec51e88a38f9be4e6f3" FOREIGN KEY ("product_type_id") REFERENCES "product_type"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product" ADD CONSTRAINT "FK_9c47355777d0ea7c76aa31059cd" FOREIGN KEY ("product_type_id") REFERENCES "product_type"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product" ADD CONSTRAINT "FK_0dce9bc93c2d2c399982d04bef1" FOREIGN KEY ("category_id") REFERENCES "category"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_variant_image" ADD CONSTRAINT "FK_69000ecf433a3a1f776b73fd187" FOREIGN KEY ("product_variant_id") REFERENCES "product_variant"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_variant" ADD CONSTRAINT "FK_ca67dd080aac5ecf99609960cd2" FOREIGN KEY ("product_id") REFERENCES "product"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "package_item" ADD CONSTRAINT "FK_8ecebd98573b36ad2bc47121bdc" FOREIGN KEY ("product_id") REFERENCES "product"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "package_item" ADD CONSTRAINT "FK_1757006eced906119315086de61" FOREIGN KEY ("product_variant_id") REFERENCES "product_variant"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "quotation_item" ADD CONSTRAINT "FK_303cbbaa0114a41cd6654a0af14" FOREIGN KEY ("quotation_id") REFERENCES "quotation"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "quotation_item" ADD CONSTRAINT "FK_a224f30e0a736c561070848d43d" FOREIGN KEY ("product_id") REFERENCES "product_variant"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "quotation_item" ADD CONSTRAINT "FK_422cdff7f048a4dbf7f4b639f14" FOREIGN KEY ("package_id") REFERENCES "package_item"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_87b8888186ca9769c960e926870" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_b23c65e50a758245a33ee35fda1" FOREIGN KEY ("role_id") REFERENCES "role"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "variant_option_values" ADD CONSTRAINT "FK_05d823f52ff66d4149a5cd784db" FOREIGN KEY ("product_variant_id") REFERENCES "product_variant"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "variant_option_values" ADD CONSTRAINT "FK_0f99ccde035292117268b3fa2a7" FOREIGN KEY ("product_option_value_id") REFERENCES "product_option_value"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "variant_option_values" DROP CONSTRAINT "FK_0f99ccde035292117268b3fa2a7"`);
        await queryRunner.query(`ALTER TABLE "variant_option_values" DROP CONSTRAINT "FK_05d823f52ff66d4149a5cd784db"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_b23c65e50a758245a33ee35fda1"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_87b8888186ca9769c960e926870"`);
        await queryRunner.query(`ALTER TABLE "quotation_item" DROP CONSTRAINT "FK_422cdff7f048a4dbf7f4b639f14"`);
        await queryRunner.query(`ALTER TABLE "quotation_item" DROP CONSTRAINT "FK_a224f30e0a736c561070848d43d"`);
        await queryRunner.query(`ALTER TABLE "quotation_item" DROP CONSTRAINT "FK_303cbbaa0114a41cd6654a0af14"`);
        await queryRunner.query(`ALTER TABLE "package_item" DROP CONSTRAINT "FK_1757006eced906119315086de61"`);
        await queryRunner.query(`ALTER TABLE "package_item" DROP CONSTRAINT "FK_8ecebd98573b36ad2bc47121bdc"`);
        await queryRunner.query(`ALTER TABLE "product_variant" DROP CONSTRAINT "FK_ca67dd080aac5ecf99609960cd2"`);
        await queryRunner.query(`ALTER TABLE "product_variant_image" DROP CONSTRAINT "FK_69000ecf433a3a1f776b73fd187"`);
        await queryRunner.query(`ALTER TABLE "product" DROP CONSTRAINT "FK_0dce9bc93c2d2c399982d04bef1"`);
        await queryRunner.query(`ALTER TABLE "product" DROP CONSTRAINT "FK_9c47355777d0ea7c76aa31059cd"`);
        await queryRunner.query(`ALTER TABLE "category" DROP CONSTRAINT "FK_a6d080a3ec51e88a38f9be4e6f3"`);
        await queryRunner.query(`ALTER TABLE "product_option" DROP CONSTRAINT "FK_e634fca34f6b594b87fdbee95f6"`);
        await queryRunner.query(`ALTER TABLE "product_option_value" DROP CONSTRAINT "FK_975b6e2a1b5de96875fa1c84413"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0f99ccde035292117268b3fa2a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_05d823f52ff66d4149a5cd784d"`);
        await queryRunner.query(`DROP TABLE "variant_option_values"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b23c65e50a758245a33ee35fda"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_87b8888186ca9769c960e92687"`);
        await queryRunner.query(`DROP TABLE "user_roles"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c839fa149d39efa6217eee7414"`);
        await queryRunner.query(`DROP TABLE "file"`);
        await queryRunner.query(`DROP TABLE "quotation"`);
        await queryRunner.query(`DROP TABLE "quotation_item"`);
        await queryRunner.query(`DROP TABLE "package_item"`);
        await queryRunner.query(`DROP TABLE "product_variant"`);
        await queryRunner.query(`DROP TABLE "product_variant_image"`);
        await queryRunner.query(`DROP TABLE "product"`);
        await queryRunner.query(`DROP TYPE "public"."product_item_type_enum"`);
        await queryRunner.query(`DROP TABLE "package_detail"`);
        await queryRunner.query(`DROP TABLE "product_type"`);
        await queryRunner.query(`DROP TABLE "category"`);
        await queryRunner.query(`DROP TABLE "product_option"`);
        await queryRunner.query(`DROP TABLE "product_option_value"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ab4a80281f1e8d524714e00f38"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_78a916df40e02a9deb1c4b75ed"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e12875dfb3b1d92d7d7c5377e2"`);
        await queryRunner.query(`DROP TABLE "user"`);
        await queryRunner.query(`DROP TABLE "role"`);
    }

}
